### ISSUE TITLE
fastleds rainbox Mode aus Profile in ambobox

### ISSUE THREAD

**Issue by KiWy86** [dmadison/Adalight-FastLED#22] opened 2020-04-02 23:21 UTC
is it possible to integrate a rainbow mode into the arduino code? as normally available in the fastLED. or is that only possible by creating a profile in ambibox or via a dll?

**Comment by dmadison** [comment] 2020-04-03 03:35
Closing as duplicate of #21

**Closed as completed by dmadison** 2020-04-03 03:35 UTC
